# Generated by Django 3.1 on 2022-01-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20220125_0754'),
        ('cart', '0002_auto_20220122_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(related_name='cart_items', to='store.Variation'),
        ),
    ]
