# Generated by Django 3.1 on 2022-02-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20220129_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(default='Draft', max_length=20),
        ),
    ]
